name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for Nest.js backend
        run: npm install
        working-directory: backend

      - name: Start Nest.js server
        run: npm run start --if-present
        working-directory: backend

      - name: Wait for Nest.js server to start
        run: |
          while [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:3005) -ne 200 ]; do
            sleep 2
          done

      - name: start pm2
        run: pm2 reload 0

        